parser: '@typescript-eslint/parser'

parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
        jsx: true
        experimentalObjectRestSpread: true
    project: './tsconfig.json'

settings:
    jsdoc:
        mode: typescript
    react:
        createClass: "Component"
        pragma: "h"
        version: "16.3"

env:
    browser: true
    commonjs: true
    es6: true
    jquery: true

plugins:
    - jsdoc
    - react
    - react-hooks
    - '@typescript-eslint'

globals:
    App: true
    Foundation: true
    require: false
    __DEBUG__: true

extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:react-hooks/recommended'
    - 'plugin:jsdoc/recommended'

rules:
    indent:
        - error
        - tab
    linebreak-style:
        - error
        - unix
    semi:
        - error
        - always

    # JSDoc
    'jsdoc/check-alignment': warn
    'jsdoc/check-param-names': error
    'jsdoc/check-syntax': warn
    'jsdoc/check-tag-names':
        - warn
        - definedTags: ["internal"]
    'jsdoc/check-types': warn
    'jsdoc/newline-after-description': warn
    'jsdoc/no-types': warn
    'jsdoc/require-jsdoc': off
    'jsdoc/require-param-name': off
    'jsdoc/require-param-type': off
    'jsdoc/require-param-description': off
    'jsdoc/require-param': off
    'jsdoc/require-returns-check': warn
    'jsdoc/require-returns-type': off
    'jsdoc/require-returns': off
    'jsdoc/valid-types': warn
