name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   uses: actions/setup-node@v2-beta
                with:
                    node-version: '14'

            -   uses: pnpm/action-setup@v1.2.0
                with:
                    version: '^5.8.0'
                    run_install: true

            -   run: pnpm test

            -   name: Prettify package.json
                run: pnpx prettier-package-json --use-tabs --list-different
